[package]
name = "rust-namer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
thirtyfour = "0.31.0"
tokio = { version = "1.36.0", features = ["full"] }
